site_name: RocketDevs Help
site_url: https://rocketdevs.com
theme:
  favicon: assets/rockets.png
  logo: assets/rockets.png
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: red
      accent: orange 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: red
      accent: orange
nav:
  - Blog:
    - blog/index.md
  - Why RocketDevs?: index.md
  - RocketLevels: HiringGuide.md
  - Screening Process: TechnicalScreeningProcess.md
  - I found a Dev!: IFoundaDev.md
  - FAQ: FAQS.md
plugins:
  - blog:
      post_date_format: full
      post_url_date_format: yyyy/MM/dd
  - rss:
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags 
markdown_extensions:
  - attr_list
  - md_in_html
copyright: |
  &copy; 2023 <a href="https://linkedin.com/in/thelastsultan"  target="_blank" rel="noopener">RocketDevs Help</a>
