name: Build and Deploy

on:
  push:
    branches:
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.17

      - name: Install dependencies
        run: pip install mkdocs mkdocs-material==9.2.0b3 awscli mkdocs-rss-plugin

      - name: Build documentation
        run: mkdocs build

      - name: Sync to S3
        run: aws s3 sync ./site s3://help.rocketdevs.com
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Invalidate CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id E3RXGRXS0CORHQ --paths "/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}